doctrine:
  orm:
    mappings:
      Grr\GrrBundle:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/Grr/GrrBundle/Entity'
        prefix: 'Grr\GrrBundle\Entity'
        alias: GrrGrrBundle
