doctrine:
  orm:
    mappings:
      Grr\GrrBundle:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/Grr/GrrBundle/src/Entity'
        prefix: 'Grr\GrrBundle'
        alias: GrrGrrBundle

    resolve_target_entities:
      Grr\Core\Contrat\Entity\AreaInterface: Grr\GrrBundle\Entity\Area
      Grr\Core\Contrat\Entity\RoomInterface: Grr\GrrBundle\Entity\Room
      Grr\Core\Contrat\Entity\EntryInterface: Grr\GrrBundle\Entity\Entry
      Grr\Core\Contrat\Entity\EntryTypeInterface: Grr\GrrBundle\Entity\EntryType
      Grr\Core\Contrat\Entity\PeriodicityInterface: Grr\GrrBundle\Entity\Periodicity
      Grr\Core\Contrat\Entity\Security\UserInterface: Grr\GrrBundle\Entity\Security\User
      Grr\Core\Contrat\Entity\Security\AuthorizationInterface: Grr\GrrBundle\Entity\Security\Authorization