twig:
  form_themes: ['bootstrap_4_layout.html.twig', 'form/grr_types.html.twig']
  paths:
    '%kernel.project_dir%/src/Grr/GrrBundle/templates/admin': grr_admin
    '%kernel.project_dir%/src/Grr/GrrBundle/templates/front': grr_front
    '%kernel.project_dir%/src/Grr/GrrBundle/templates/security': grr_security
    '%kernel.project_dir%/src/Grr/GrrBundle/templates/default': grr_default
    '%kernel.project_dir%/src/Grr/GrrBundle/public/images': images
    '%kernel.project_dir%/src/Grr/GrrBundle/public/css': css
