#doctrine:
orm:
  auto_generate_proxy_classes: true
  naming_strategy: doctrine.orm.naming_strategy.underscore
  auto_mapping: true
  mappings:
    Grr\GrrBundle:
      is_bundle: false
      type: annotation
      dir: '%kernel.project_dir%/src/Grr/GrrBundle/Entity'
      prefix: 'Grr\GrrBundle\Entity'
      alias: GrrGrrBundle
